resources:
  - name: email-resource-source
    type: git
    source:
      uri: https://github.com/pivotal-cf/email-resource
      branch: master
  - name: send-an-email
    type: email
    source:
      smtp:
        host: {{smtp-host}}
        port: {{smtp-port}}
        username: {{smtp-username}}
        password: {{smtp-password}}
      from: {{email-from}}
      to: [ {{email-to}} ]

resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource

jobs:
  - name: demo-email-an-artifact-sha
    plan:
      - get: email-resource-source
        trigger: false
      - task: demo-prep-sha-email
        file: email-resource-source/ci/demo-prep-sha-email.yml
        config:
          params:
            file_to_hash: email-resource-source/Dockerfile
            output_subject_file: generated-subject
            output_body_file: generated-body
      - put: send-an-email
        params:
          subject: email-out/generated-subject
          body_file: email-out/generated-body
