resources:
- name: source
  type: git
  source:
    uri: git@github.com:pivotal-cf/email-resource.git
    branch: ((dev-build-branch))
    private_key: ((git-ssh-key))

- name: docker-registry
  type: docker-image
  source:
    repository: ((docker-repository))
    username: ((docker-registry-username))
    password: ((docker-registry-password))
    tag: ((docker-dev-build-tag))

jobs:
- name: test-and-build
  plan:
    - in_parallel:
      - get: source
        trigger: true
    - task: test
      file: source/ci/tasks/runTests.yml
    - task: build
      file: source/ci/tasks/build.yml
      params:
        DEV: true
    - put: docker-registry
      params:
        build: compiled-output
