groups:
- name: compile
  jobs:
  - test-and-build
- name: deploy
  jobs:
  - deploy

resources:
- name: source
  type: git
  source:
    uri: git@github.com:pivotal-cf/email-resource.git
    branch: master
    private_key: ((git-ssh-key))

- name: draft-email-resource
  type: github-release
  source:
    owner: pivotal-cf
    repository: email-resource
    access_token: ((github-token))
    drafts: true

- name: releases
  type: github-release
  source:
    owner: pivotal-cf
    repository: email-resource
    access_token: ((github-token))

- name: docker-registry
  type: docker-image
  source:
    repository: ((docker-repository))
    username: ((docker-registry-username))
    password: ((docker-registry-password))
    tag: ((docker-tag))

jobs:
- name: test-and-build
  plan:
    - in_parallel:
      - get: source
        trigger: true
    - task: test
      file: source/ci/tasks/runTests.yml
    - task: build
      file: source/ci/tasks/build.yml
    - put: draft-email-resource
      params:
        name: compiled-output/name
        tag: compiled-output/tag

        globs:
        - compiled-output/bin/in
        - compiled-output/bin/out
        - compiled-output/bin/check
- name: deploy
  plan:
    - in_parallel:
      - get: source
      - get: releases
        trigger: true
    - task: prepare
      file: source/ci/tasks/prepare.yml
    - put: docker-registry
      params:
        build: output
        tag_as_latest: true
        tag: output/version
