name: develop ci action

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17.6'
      - run: go get github.com/xchapter7x/versioning
      - shell: bash
        run: |
          DRAFT_VERSION=`versioning bump_patch`-`git rev-parse HEAD`
          go build -o bin/check ./check/cmd
          go build -o bin/in ./in/cmd
          go build -o bin/out -ldflags "-X main.VERSION=${DRAFT_VERSION}" ./out/cmd
      # - run: go test -v ./...